# Generated by Django 4.0.4 on 2022-04-25 12:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.BooleanField()),
                ('name', models.TextField(default='NAME', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='DATANAME', max_length=30)),
                ('directory_to_label', models.TextField(default='DIR_LABEL', max_length=30)),
                ('directory_to_test', models.TextField(default='DIR_TEST', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquetador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=2)),
                ('n', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('name', models.TextField(default='NAME', max_length=20)),
                ('test_passed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.IntegerField()),
                ('nombre_clase', models.TextField(default='NOMBRE_CLASE', max_length=30)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.data')),
                ('etiquetador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.etiquetador')),
            ],
        ),
        migrations.CreateModel(
            name='Datatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='NAME', max_length=30)),
                ('label', models.TextField(default='LABEL', max_length=30)),
                ('datas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='labeling.datas')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='datas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_data', to='labeling.datas'),
        ),
    ]
