# Generated by Django 4.0.4 on 2022-04-27 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling', '0002_datas_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetador',
            name='datas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labeling.datas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiquetador',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
