# Generated by Django 4.0.4 on 2022-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_etiquetador_datas_etiquetador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetador',
            name='datatest',
            field=models.ManyToManyField(to='labeling.datatest'),
        ),
    ]
