# Generated by Django 4.0.4 on 2022-04-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_etiquetador_datatest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.IntegerField()),
                ('nombre_clase', models.TextField(default='NOMBRE_CLASE', max_length=30)),
                ('datatest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.datatest')),
                ('etiquetador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.etiquetador')),
            ],
        ),
    ]
