# Generated by Django 4.0.4 on 2022-04-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_labeltest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltest',
            old_name='datatest',
            new_name='remain_datatest',
        ),
    ]
